# 1.
Cxx=g++
# 2.
CXXFLAGS = -I/usr/local/include/ -I/usr/local/include/opencv2 -O0 -g3 -Wall -c
# 3.
LIBS = -L/usr/lib -lpwm -lwiringPi -lrt -lpthread -ldl -lm -std=gnu++0x -std=c++0x -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_video -lraspicam -lraspicam_cv -lopencv_core
 

# 7. the real mess
.PHONY: all  filtre acqui acqui_v2 acqui_v3 test_ultrason
# for make all
all: filtre acqui acqui_v2 acqui_v3 test_ultrason
 
  
test_ultrason: test_ultrason.o
	@echo 'Building test_ultrason='
	$(CXX) -o test_ultrason test_ultrason.o $(LIBS)
	@echo 'Building Finished:'
 
filtre: filtre.o
	@echo 'Building filtre='
	$(CXX) -o filtre filtre.o $(LIBS)
	@echo 'Building Finished:'
 
 acqui: acqui.o
	@echo 'Building acqui='
	$(CXX) -o acqui acqui.o $(LIBS)
	@echo 'Building Finished:'
	
  acqui_v2: acqui_v2.o
	@echo 'Building acqui_v2='
	$(CXX) -o acqui_v2 acqui_v2.o $(LIBS)
	@echo 'Building Finished:'
		
  acqui_v3: acqui_v3.o
	@echo 'Building acqui_v3='
	$(CXX) -o acqui_v3 acqui_v3.o $(LIBS)
	@echo 'Building Finished:'
		
	
# for make clean , cleaning all the build forceuly delete all the files generated by the build process
clean:
	rm -rf test_ultrason test_ultrason.o filtre.o filtre acqui acqui.o acqui_v2 acqui_v2.o acqui_v3.o
	@echo 'Clean FInished!'
 
%.d: %.cpp
	$(CXX) -MM -MF $@ $<
 
%.o: %.d
 
-include $(OBJS:.o=.d)

